### ISSUE TITLE
windows自带的控制台无法显示

### ISSUE THREAD

**Issue by chenyinchang** [alishtory/qrcode-terminal#2]
在第三方的控制台下很好用，但windows自带的控制台无法显示，无法转义序列，有什么好的办法吗？

**Comment by alishtory** [comment]
cmder试试

**Comment by MikuPy2001** [comment]
import qrcode
qr = qrcode.QRCode()
qr.add_data("https://baidu.com")
#invert=True白底黑块,有些app不识别黑底白块.
qr.print_ascii(invert=True)

请
